fos_user_profile_show:
    pattern: /
    defaults : { _controller :FOSUserBundle:Profile:show }
    requirements:
        _method: GET

fos_user_profile_edit:
    pattern: /edit
    defaults : { _controller :FOSUserBundle:Profile:edit }
    requirements:
        _method: GET|POST