fos_user_security_login:
    pattern: /connexion
    defaults : { _controller :FOSUserBundle:Security:login }

fos_user_security_check:
    pattern: /connexion_check
    defaults : { _controller :FOSUserBundle:Security:check }

fos_user_security_logout:
    pattern: /deconnexion
    defaults : { _controller :FOSUserBundle:Security:logout }